[package]
name = "norma-site-wasm"
version = "0.1.0"
authors = ["Gabriel Barbosa Fernandes <fernandesbgabriel@gmail.com>"]
edition = "2018"
license = "MIT"
categories = ["mathematics", "science", "simulation"]
description = """
Webpage for education on the Norma Machines.
"""

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_json = "1.0.68"
pest = "2.5.5"
norma_machine_rs = {git = "https://github.com/GabrielBFern/norma-machine-rs", branch="main"}
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
js-sys = "0.3.57"
lazy_static = "1.4.0"
getrandom = { version = "0.2.6", features = ["js"] }



[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]



[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"